# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 708e8ca88802e9e502531ae89af7e9b5e4ab4d73ac06456594dc248699b103598c4183878f5c8cddfd3a8eb380afa71c5c6585b5378eb22e7420315bb8389777

test:
  secret_key_base: b02f11f5722aa209883e649c7478ed4e942b5581c0fa74449bb59ff8e87fd84d6362743bec65658357c78fee055239a691857bc42b63a1424daee2282f11814e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
